[package]
name = "midden"
version = "0.1.0"
edition = "2024"

[dependencies]
elessar = { path = "../../libs/elessar" }
bandy = { path = "../../libs/bandy" }
unafs = { path = "../../libs/unafs" }
anyhow = "1.0"
gtk4 = { version = "0.10.3", features = ["v4_12"] }
glib = "0.21"
