[workspace]
resolver = "2"

members = [
    "libs/gneiss_pal",
    "apps/vein",
    "apps/stria",
    "apps/midden",
    "apps/vug",
    "apps/aulÃ«",
    "apps/amber_bytes",
    "apps/cli/vertex",
    "unaos/builder",
    "unaos/crates/kernel",
    "unaos/crates/compat",
    "unaos/crates/loader",
    "unaos/crates/userspace"
]

# OPTIMIZATION: Shared Profile Settings
# Makes all apps build faster and smaller
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
strip = true
codegen-units = 1
