[workspace]
resolver = "2"
members = [
    "libs/gneiss_pal",
    "libs/quartzite",
    "libs/elessar",
    "handlers/vein",
    "handlers/matrix",
    "handlers/vaire",
    "handlers/aule",
    "handlers/tabula",
    "handlers/midden",
    "handlers/aether",
    "handlers/amber_bytes",
    "handlers/cli",
    "handlers/comscan",
    "handlers/facet",
    "handlers/geode",
    "handlers/holocron",
    "handlers/mica",
    "handlers/obsidian",
    "handlers/principia",
    "handlers/stria",
    "handlers/vug",
    "handlers/xenolith",
    "apps/lumen",
    "apps/una"
]
