[package]
name = "tabula"
version = "0.1.0"
edition = "2024"

[dependencies]
libspelling = "0.4.1"
elessar = { path = "../../libs/elessar" }
gtk4 = { version = "0.10.3", features = ["v4_12"] }
glib = "0.21"
sourceview5 = "0.10.0"
