[package]
name = "sentinel"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "sentinel"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
regex = "1.10"
colored = "2.0"
elessar = { path = "../../libs/elessar" }
