[package]
name = "matrix"
version = "0.1.0"
edition = "2021"

[dependencies]
elessar = { path = "../../libs/elessar" }
gtk4 = { version = "0.9.7", features = ["v4_12"] }
glib = "0.20"
async-channel = "2.1"
log = "0.4"
