[package]
name = "lumen"
version = "0.1.0"
edition = "2021"

[dependencies]
elessar = { path = "../../libs/elessar" }
vein = { path = "../../handlers/vein" }
gtk4 = { version = "0.9.7", features = ["v4_12"] }
glib = "0.20"
async-channel = "2.1"
log = "0.4"
env_logger = "0.10"
dotenvy = "0.15"
