[package]
name = "lumen"
version = "0.1.0"
edition = "2024"

[features]
default = ["gtk"]
gtk = ["vein/gtk", "elessar/gtk"]
gnome = ["vein/gnome", "elessar/gnome", "dep:libadwaita"]

[dependencies]
elessar = { path = "../../libs/elessar" }
vein = { path = "../../handlers/vein" }
gtk4 = { version = "0.10.3", features = ["v4_12"] }
glib = "0.21"
async-channel = "2.5"
log = "0.4"
env_logger = "0.11"
dotenvy = "0.15"
libadwaita = { version = "0.8.1", features = ["v1_4"], optional = true }
