[package]
name = "aule"
version = "0.1.0"
edition = "2024"

[dependencies]
elessar = { path = "../../libs/elessar" }
gtk4 = { version = "0.10.3", features = ["v4_12"] }
glib = "0.21"
async-channel = "2.5"
