[package]
name = "unafs-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "unafs"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
gneiss_pal = { path = "../../../libs/gneiss_pal" }
unafs = { path = "../../../libs/unafs" }
