[package]
name = "vein"
version = "0.1.0"
edition = "2021"

[dependencies]
# Pointing to the new location in libs/
gneiss_pal = { path = "../../libs/gneiss_pal" }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.36", features = ["full"] }
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ab_glyph = "0.2.32"
