[package]
name = "vein"
version = "0.1.0"
edition = "2024"

[features]
default = ["gtk"]
gtk = ["elessar/gtk"]
gnome = ["elessar/gnome", "dep:libadwaita"]

[dependencies]
elessar = { path = "../../libs/elessar" }
bandy = { path = "../../libs/bandy" }
gtk4 = { version = "0.10.3", features = ["v4_12"] }
glib = "0.21"
libadwaita = { version = "0.8.1", features = ["v1_4"], optional = true }
sourceview5 = "0.10"
async-channel = "2.5"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.13", features = ["json", "stream", "multipart"] }
chrono = "0.4"
tokio = { version = "1.49", features = ["full"] }
# vug = { path = "../vug" }
anyhow = "1.0.102"
